version: '3'

services:
  fast_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'uvicorn api.main:app --host 0.0.0.0'
    restart: always
    volumes:
      - './:/app'
    depends_on:
      - postgres
    ports:
      - 5677:8000

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
